module.exports = [ { metadata:[ "SpHtml",
      "/components/examples/Html.js",
      true,
      null ],
    settings:{ fields:[ { name:"content",
          required:true,
          label:"msg_published_content",
          rows:6,
          type:"textarea" },
        { name:"draft",
          label:"msg_draft_content",
          rows:6,
          type:"textarea" } ] } },
  { metadata:[ "SpHelloWorld",
      "/spcomponents/HelloWorld.js",
      false,
      null ],
    settings:null },
  { metadata:[ "SpRSSViewer",
      "/spcomponents/RSSViewer.js",
      false,
      null ],
    settings:{ fields:[ { name:"feedUrl",
          type:"text",
          label:"feedUrl" } ] } },
  { metadata:[ "Echo",
      "/components/Echo.js",
      false,
      null ],
    settings:null } ]